CONFIG_POSIX_API=y
CONFIG_SHELL=y
CONFIG_POSIX_UNAME_SHELL=y
CONFIG_MP_MAX_NUM_CPUS=1
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_LITTLEFS=y
CONFIG_FILE_SYSTEM_SHELL=y
CONFIG_FILE_SYSTEM_MKFS=y
CONFIG_FILE_SYSTEM_SHELL_TEST_COMMANDS=y
CONFIG_HEAP_MEM_POOL_SIZE=131072
CONFIG_ZVFS_OPEN_MAX=16
